# Generated by Django 5.0.4 on 2024-04-25 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('users', '0004_alter_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='computer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.computer'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='computer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='device.computer'),
        ),
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
