# Generated by Django 5.0.4 on 2024-04-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_reservation_computer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='computer_id',
        ),
    ]
